### ISSUE TITLE
javadoc path in pom.xml

### ISSUE THREAD

**Issue by esgn** [indyteo/WebServerAPI#1]
I would replace `<javadocExecutable>${java.home}/../bin/</javadocExecutable>` by `<javadocExecutable>${java.home}/bin/</javadocExecutable>` in `pom.xml`. 
Usually `JAVA_HOME` is the path to the Java installation directory and `$JAVA_HOME/bin` (or `%JAVA_HOME%\bin` for windows)  is then added to the PATH.

**Comment by indyteo** [comment]
Fixed by leaving default config (and found the original issue I had in my local environment that made me do that in the first place :smile:)
